application: cm-kang
version: 12
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /rss
  script: diff.py

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /.*
  script: diff.py